config/routes.rb
Rails.application.routes.draw do
  
  #get 'tops/index'

  root 'tops#index'
  
  
  
  resources :inquiries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :blogs do
    
    collection do
      post :confirm
    end
    
  end
  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :content, presence: true,length: { maximum: 140 } 
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    
    validates :content, presence: true,length: { maximum: 140 } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:edit, :update ,:destroy]
  
    
    #一覧画面表示
    def index
       @blogs=Blog.all.order(id: :asc)
    end
    
    #新規画面表示
    def new 
    
        if params[:back]
          @blog = Blog.new(blog_params)
          
        else
          @blog=Blog.new
          
        end
    
    end
    
    
    #更新画面表示
    def edit
    end
    
    #閲覧だけの画面は不要？
    
    
    #確認画面表示
    def confirm
        @blog = Blog.new(blog_params)
        render 'new' if @blog.invalid?
    end
    
    
    #新規登録処理
    def create
        
        @blog=Blog.create(blog_params)
        if @blog.save==true
        
            redirect_to blogs_path, notice: "ブログを作成しました。"
            
        else
            render("new")
        end
    
    end
    
    #更新時処理
    def update
        
        if @blog.update(blog_params)==true
            
            redirect_to blogs_path, notice: "ブログを編集しました。"
        
        else
            
            render 'edit'
        end
    end
    
    #削除時処理
    def destroy
        @blog.destroy
        redirect_to blogs_path,notice:"ブログを削除しました"
        
    end
    
    
    private
    
    
    def blog_params
        params.require(:blog).permit(:title,:content)
    end
    
    def set_blog
        @blog = Blog.find(params[:id])
    end

    
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController


#今回は「new」と「create」のみ
#(一覧画面は不要)
  # GET /inquiries/new
  def new
    @inquiry = Inquiry.new
  end
  
  # POST /inquiries
  # POST /inquiries.json
  def create
    @inquiry = Inquiry.create(inquiry_params)
    
    if @inquiry.save == true
      #登録に成功した場合
      redirect_to new_inquiry_path #, notice: "問い合わせ内容を登録しました。"
      
    else
      #登録に失敗した場合
      # 入力フォームを再描画します。
      render "new"
      
    end
    
    
=begin
↓は自動作成されたもの……とりあえず無効化
    @inquiry = Inquiry.new(inquiry_params)

    respond_to do |format|
      if @inquiry.save
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully created.' }
        format.json { render :show, status: :created, location: @inquiry }
      else
        format.html { render :new }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
=end

  end


=begin
  # GET /inquiries
  # GET /inquiries.json
  def index
    @inquiries = Inquiry.all
  end

  # GET /inquiries/1
  # GET /inquiries/1.json
  def show
  end


  # GET /inquiries/1/edit
  def edit
  end

  # PATCH/PUT /inquiries/1
  # PATCH/PUT /inquiries/1.json
  def update
    respond_to do |format|
      if @inquiry.update(inquiry_params)
        format.html { redirect_to @inquiry, notice: 'Inquiry was successfully updated.' }
        format.json { render :show, status: :ok, location: @inquiry }
      else
        format.html { render :edit }
        format.json { render json: @inquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inquiries/1
  # DELETE /inquiries/1.json
  def destroy
    @inquiry.destroy
    respond_to do |format|
      format.html { redirect_to inquiries_url, notice: 'Inquiry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inquiry
      @inquiry = Inquiry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inquiry_params
      params.require(:inquiry).permit(:name, :email, :content)
    end

=end

private

  def inquiry_params
    params.require(:inquiry).permit(:name,:email,:content)
  end
  
  def set_inquiry
    @inquiry =Inquiry.find(params[:id])
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    
  def choose_new_or_edit
    
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
    
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true , url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  
  <%= form.submit %>

<% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog,url: blogs_path,  local: true) do |form| %>
  
  
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>


  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  
  <%= form.submit  "登録する" %>
  
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit  "もどる", name: 'back' %> 


<% end %>

app/views/blogs/edit.html.erb
 <h2>ブログを作成する</h2>


<%= render 'form' %>

<div></div>

<%= link_to "ブログを削除する", blog_path(@blog.id) ,
  method: :delete, data: { confirm: '本当に編集していいですか？' }  %>


<div></div>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to 'ブログ内容を確認,編集する', edit_blog_path(blog.id) %></td>
  </tr>
<% end %>

</table>


<div></div>
<div></div>

<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
 <h2>ブログを作成する</h2>


<%= render 'form' %>

<div></div>
  
<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/inquiries/_form.html.erb
<%= form_with(model: inquiry, local: true) do |form| %>
  <% if inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inquiry.errors.count, "error") %> prohibited this inquiry from being saved:</h2>

      <ul>
      <% inquiry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :inquiry_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :inquiry_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :inquiry_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inquiries/edit.html.erb
<h1>Editing Inquiry</h1>

<%= render 'form', inquiry: @inquiry %>

<%= link_to 'Show', @inquiry %> |
<%= link_to 'Back', inquiries_path %>

app/views/inquiries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inquiries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inquiries.each do |inquiry| %>
      <tr>
        <td><%= inquiry.name %></td>
        <td><%= inquiry.email %></td>
        <td><%= inquiry.content %></td>
        <td><%= link_to 'Show', inquiry %></td>
        <td><%= link_to 'Edit', edit_inquiry_path(inquiry) %></td>
        <td><%= link_to 'Destroy', inquiry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inquiry', new_inquiry_path %>

app/views/inquiries/new.html.erb
<%= form_with(model: @inquiry, local: true  ) do |form| %>
  <% if @inquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= @inquiry.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @inquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="inquiry_title">
    <%= form.label :Name %>
    <%= form.text_field :name %>
  </div>
  
  <div class="inquiry_title">
    <%= form.label :Email %>
    <%= form.text_field :email %>
  </div>
  
  <div class="inquiry_title">
    <%= form.label :Content %>
    <%= form.text_field :content %>
  </div>
  
  
  <%= form.submit %>

<% end %>

app/views/inquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inquiry.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inquiry.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @inquiry.content %>
</p>

<%= link_to 'Edit', edit_inquiry_path(@inquiry) %> |
<%= link_to 'Back', inquiries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ensyuu1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tops/index.html.erb
<h1>Tops#index</h1>
<p>Find me in app/views/tops/index.html.erb</p>


<%= link_to 'ブログへ', blogs_path %>


<%= link_to '問い合わせする',new_inquiry_path %>